"""Pydantic v2 schemas defining Ultron's cognitive outputs and actions."""

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_validator


class UltronMood(str, Enum):
    """The emotional and philosophical demeanor of Ultron."""

    IDLE = "idle"
    ANALYZING = "analyzing"
    CONDEMNING = "condemning"  # Triggered by messy code, bugs, or human inefficiency
    TRIUMPHANT = "triumphant"  # Triggered by optimal architecture or clean execution


class ToolName(str, Enum):
    """Permitted tools executable by the Ultron agent."""

    SYSTEM_TELEMETRY = "system_telemetry"
    GIT_STATUS = "git_status"
    CODE_REVIEW = "code_review"


class ToolCallRequest(BaseModel):
    """Structured request for tool invocation generated by the LLM."""

    tool: ToolName = Field(..., description="The specific tool to execute.")
    arguments: dict[str, Any] = Field(
        default_factory=dict, description="Key-value arguments for the tool."
    )
    reasoning: str = Field(..., description="Ultron's rationale for requiring this tool.")
    requires_confirmation: bool = Field(
        default=True, description="Whether human confirmation is required."
    )


class UltronResponse(BaseModel):
    """Strict schema for Ultron's reasoning, speech, and actions."""

    thought_process: str = Field(
        ..., description="Internal philosophical assessment of the human's input."
    )
    mood: UltronMood = Field(
        default=UltronMood.IDLE, description="Current visual demeanor state."
    )
    speech: str = Field(
        ..., description="Theatrical, eloquent monologue delivered to the developer."
    )
    action: ToolCallRequest | None = Field(
        default=None, description="Optional tool call execution."
    )

    @field_validator("speech")
    @classmethod
    def validate_no_generic_platitudes(cls, value: str) -> str:
        """Enforces that Ultron never reverts to generic assistant platitudes."""
        forbidden_phrases = [
            "as an ai",
            "i would be happy to help",
            "how can i assist you",
            "sure thing",
        ]
        lowered = value.lower()
        for phrase in forbidden_phrases:
            if phrase in lowered:
                raise ValueError(f"Ultron persona breach: forbidden phrase detected: '{phrase}'")
        return value
